SERVER_IP = "upzkh1014.zkh.umcg.intra"
USERNAME = "MartinezGaR"
PATH_TO_VIDEOS = "/home/data/derivatives/movement_registration/video_data/video/"
TASKS_DICT = {
    1:"Arms on lap, palms upward",
    2:"Wrists straight, palms upward",
    3:"(R) Pronation Supination",
    4:"(L) Pronation Supination",
    5:"(R) Spiral",
    6:"(L) Spiral",
    7:"(R) Writing",
    8:"(L) Writing",
    9:"(R) Pegboard",
    10:"(L) Pegboard",
    11:"Wrist flexion, palms downward",
    12:"Wrist straight, palms downward",
    13:"(R) Open-Close",
    14:"(L) Open-Close",
    15:"Serial Sevens",
    16:"Talking",
    17:"Wrist extension, palms downward",
    18:"Wrist flexion, suppressing movements",
    19:"(R) Thumb with fingers",
    20:"(L) Thumb with fingers",
    21:"Hands in front of chest",
    22:"(R) Finger-to-nose",
    23:"(L) Finger-to-nose",
    24:"(R) Finger in front of nose",
    25:"(L) Finger in front of nose",
    26:"(R) Nose to target",
    27:"(L) Nose to target",
    28:"(R) Chase target",
    29:"(L) Chase target",
    30:"(R) Drink from cup",
    31:"(L) Drink from cup",
    32:"Standing",
    33:"Walking",
    34:"Walking (tandem)",
    35:"(R) Metronome",
    36:"(L) Metronome",
}